/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EntretienRouteImport } from './routes/entretien'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConditionsGeneralesRouteImport } from './routes/conditions-generales'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalerieIndexRouteImport } from './routes/galerie.index'
import { Route as CreationsIndexRouteImport } from './routes/creations.index'
import { Route as ArtisanesIndexRouteImport } from './routes/artisanes.index'
import { Route as GalerieSlugRouteImport } from './routes/galerie.$slug'
import { Route as CreationsIdRouteImport } from './routes/creations.$id'
import { Route as ArtisanesIdRouteImport } from './routes/artisanes.$id'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCreationsRouteImport } from './routes/admin.creations'
import { Route as AdminCommandesRouteImport } from './routes/admin.commandes'
import { Route as AdminArtisanesRouteImport } from './routes/admin.artisanes'

const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretienRoute = EntretienRouteImport.update({
  id: '/entretien',
  path: '/entretien',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesRoute = ConditionsGeneralesRouteImport.update({
  id: '/conditions-generales',
  path: '/conditions-generales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieIndexRoute = GalerieIndexRouteImport.update({
  id: '/galerie/',
  path: '/galerie/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsIndexRoute = CreationsIndexRouteImport.update({
  id: '/creations/',
  path: '/creations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanesIndexRoute = ArtisanesIndexRouteImport.update({
  id: '/artisanes/',
  path: '/artisanes/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieSlugRoute = GalerieSlugRouteImport.update({
  id: '/galerie/$slug',
  path: '/galerie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsIdRoute = CreationsIdRouteImport.update({
  id: '/creations/$id',
  path: '/creations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanesIdRoute = ArtisanesIdRouteImport.update({
  id: '/artisanes/$id',
  path: '/artisanes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreationsRoute = AdminCreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtisanesRoute = AdminArtisanesRouteImport.update({
  id: '/artisanes',
  path: '/artisanes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/entretien': typeof EntretienRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/panier': typeof PanierRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/recherche': typeof RechercheRoute
  '/admin/artisanes': typeof AdminArtisanesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/creations': typeof AdminCreationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/artisanes/$id': typeof ArtisanesIdRoute
  '/creations/$id': typeof CreationsIdRoute
  '/galerie/$slug': typeof GalerieSlugRoute
  '/artisanes/': typeof ArtisanesIndexRoute
  '/creations/': typeof CreationsIndexRoute
  '/galerie/': typeof GalerieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/entretien': typeof EntretienRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/panier': typeof PanierRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/recherche': typeof RechercheRoute
  '/admin/artisanes': typeof AdminArtisanesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/creations': typeof AdminCreationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/artisanes/$id': typeof ArtisanesIdRoute
  '/creations/$id': typeof CreationsIdRoute
  '/galerie/$slug': typeof GalerieSlugRoute
  '/artisanes': typeof ArtisanesIndexRoute
  '/creations': typeof CreationsIndexRoute
  '/galerie': typeof GalerieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/entretien': typeof EntretienRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/panier': typeof PanierRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/recherche': typeof RechercheRoute
  '/admin/artisanes': typeof AdminArtisanesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/creations': typeof AdminCreationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/artisanes/$id': typeof ArtisanesIdRoute
  '/creations/$id': typeof CreationsIdRoute
  '/galerie/$slug': typeof GalerieSlugRoute
  '/artisanes/': typeof ArtisanesIndexRoute
  '/creations/': typeof CreationsIndexRoute
  '/galerie/': typeof GalerieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/conditions-generales'
    | '/confidentialite'
    | '/contact'
    | '/entretien'
    | '/faq'
    | '/favoris'
    | '/panier'
    | '/qui-sommes-nous'
    | '/recherche'
    | '/admin/artisanes'
    | '/admin/commandes'
    | '/admin/creations'
    | '/admin/dashboard'
    | '/artisanes/$id'
    | '/creations/$id'
    | '/galerie/$slug'
    | '/artisanes/'
    | '/creations/'
    | '/galerie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/conditions-generales'
    | '/confidentialite'
    | '/contact'
    | '/entretien'
    | '/faq'
    | '/favoris'
    | '/panier'
    | '/qui-sommes-nous'
    | '/recherche'
    | '/admin/artisanes'
    | '/admin/commandes'
    | '/admin/creations'
    | '/admin/dashboard'
    | '/artisanes/$id'
    | '/creations/$id'
    | '/galerie/$slug'
    | '/artisanes'
    | '/creations'
    | '/galerie'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/conditions-generales'
    | '/confidentialite'
    | '/contact'
    | '/entretien'
    | '/faq'
    | '/favoris'
    | '/panier'
    | '/qui-sommes-nous'
    | '/recherche'
    | '/admin/artisanes'
    | '/admin/commandes'
    | '/admin/creations'
    | '/admin/dashboard'
    | '/artisanes/$id'
    | '/creations/$id'
    | '/galerie/$slug'
    | '/artisanes/'
    | '/creations/'
    | '/galerie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConditionsGeneralesRoute: typeof ConditionsGeneralesRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  EntretienRoute: typeof EntretienRoute
  FaqRoute: typeof FaqRoute
  FavorisRoute: typeof FavorisRoute
  PanierRoute: typeof PanierRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  RechercheRoute: typeof RechercheRoute
  ArtisanesIdRoute: typeof ArtisanesIdRoute
  CreationsIdRoute: typeof CreationsIdRoute
  GalerieSlugRoute: typeof GalerieSlugRoute
  ArtisanesIndexRoute: typeof ArtisanesIndexRoute
  CreationsIndexRoute: typeof CreationsIndexRoute
  GalerieIndexRoute: typeof GalerieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretien': {
      id: '/entretien'
      path: '/entretien'
      fullPath: '/entretien'
      preLoaderRoute: typeof EntretienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales': {
      id: '/conditions-generales'
      path: '/conditions-generales'
      fullPath: '/conditions-generales'
      preLoaderRoute: typeof ConditionsGeneralesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie/': {
      id: '/galerie/'
      path: '/galerie'
      fullPath: '/galerie/'
      preLoaderRoute: typeof GalerieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations/': {
      id: '/creations/'
      path: '/creations'
      fullPath: '/creations/'
      preLoaderRoute: typeof CreationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisanes/': {
      id: '/artisanes/'
      path: '/artisanes'
      fullPath: '/artisanes/'
      preLoaderRoute: typeof ArtisanesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie/$slug': {
      id: '/galerie/$slug'
      path: '/galerie/$slug'
      fullPath: '/galerie/$slug'
      preLoaderRoute: typeof GalerieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations/$id': {
      id: '/creations/$id'
      path: '/creations/$id'
      fullPath: '/creations/$id'
      preLoaderRoute: typeof CreationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisanes/$id': {
      id: '/artisanes/$id'
      path: '/artisanes/$id'
      fullPath: '/artisanes/$id'
      preLoaderRoute: typeof ArtisanesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creations': {
      id: '/admin/creations'
      path: '/creations'
      fullPath: '/admin/creations'
      preLoaderRoute: typeof AdminCreationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artisanes': {
      id: '/admin/artisanes'
      path: '/artisanes'
      fullPath: '/admin/artisanes'
      preLoaderRoute: typeof AdminArtisanesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArtisanesRoute: typeof AdminArtisanesRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminCreationsRoute: typeof AdminCreationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtisanesRoute: AdminArtisanesRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminCreationsRoute: AdminCreationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  ConditionsGeneralesRoute: ConditionsGeneralesRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  EntretienRoute: EntretienRoute,
  FaqRoute: FaqRoute,
  FavorisRoute: FavorisRoute,
  PanierRoute: PanierRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  RechercheRoute: RechercheRoute,
  ArtisanesIdRoute: ArtisanesIdRoute,
  CreationsIdRoute: CreationsIdRoute,
  GalerieSlugRoute: GalerieSlugRoute,
  ArtisanesIndexRoute: ArtisanesIndexRoute,
  CreationsIndexRoute: CreationsIndexRoute,
  GalerieIndexRoute: GalerieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
